### ISSUE TITLE
How to run the backend?

### ISSUE THREAD

**Issue by stilet** [supertokens/auth-demo#1]
Sorry for the simple question - but how to run the backend?

**Comment by rishabhpoddar** [comment]
If you just want to see the demo, you can visit: http://demo.supertokens.io on Firefox.

Instead, if you want to run the demo on your computer, first, please make sure of the following:
- You have node installed
- You have MySQL installed and running on host host ```localhost``` and port ```3306``` (both these are defaults when you first run MySQL)
- There exists a user in MySQL with username: ```root``` and password: ```root```
- There exists a database in MySQL called ```auth_session```

After that, please do the following:
```
git clone https://github.com/supertokens/auth-demo.git
cd auth-demo
npm i -d
DOMAIN=localhost node backend/build/index.js
```
After that, please open Firefox and visit http://localhost:8080

A few notes:
- At some point in the demo, you will be asked to visit ```demo.supertokens.io/attack```. Instead, please visit ```http://localhost:8080/attack```
- If you get a MySQL error like: 
  ```
  Client does not support authentication protocol
  ```
  Please visit: https://supertokens.github.io/supertokens-node-mysql-ref-jwt/docs/troubleshooting/troubleshooting
