### ISSUE TITLE
How to get a SECRET KEY for decrypting JWT payload?

### ISSUE THREAD

**Issue by stilet** [supertokens/auth-demo#2]
Please tell me how to get a SECRET KEY for decrypting JWT payload?
For example https://jwt.io/

**Comment by rishabhpoddar** [comment]
- We use MySQL for this demo. We store the JWT secret key in the ```signing_key``` table with the key name ```access_token_signing_key```.
- One point to note is that by default, this key changes on a regular basis.
- If your question is about getting the JWT payload in the frontend, you do not need to decrypt it. The payload is base64 encoded and has the format ```<header>.<payload>.<signature>```
- The payload itself contains a few key-values that are used by our library for efficiency purposes, but one of the keys inside is ```userPayload``` which is an ```object``` containing information that was passed when creating a new session.
